### ISSUE TITLE
Can you post a working simple tutorial ?

### ISSUE THREAD

**Issue by scottstensland** [tdeheurles/homecores-reverse-proxy#1]
I am trying to solve this exact issue of launching a reverse proxy ( nginx ) as the first kubernetes pod infront of my nodejs pod and mongo pod ... I have a cluster of those two pods running fine and just need to nail the reverse-proxy pod 

First step ... launch a cluster - I use gcloud 
Next launch some backend pod - nodejs or similar ...just a hello world nodejs server
Last launch this reverse proxy <--- missing piece

I will gladly help in any way I can

**Comment by tdeheurles** [comment]
What are you exactly attempting to do ? If your cluster is on gcloud, why not use the standard way to proxy ?

By standard I mean adding `spec.type: "LoadBalancer" to your service yaml ?

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: "servicename"
spec:
  selector:
    name: "servicename"
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  type: "LoadBalancer"
```
